name: todo_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  intl: ^0.17.0
  path: ^1.8.1
  animated_splash_screen: ^1.3.0
  flutter_datetime_picker: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter


 
  flutter_lints: ^2.0.0

#   flutter_launcher_icons: ^0.9.3

# flutter_icons:
#     android: true
#     ios: true
#     image_path: assets/images/logo.png



flutter:


  uses-material-design: true


  assets:
    - assets/images/
  


